# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cf4abcce0eab4fcf41dc9750c6822cdeb4d3c73ad81f57fd8256dc8351350a65bc2a1b906991030d2c61b1d1b5d123f1ffc48850221a6e91e93e4f28d1dfe51

test:
  secret_key_base: b922b20fc5de50836c74f5722bb5c84f28e3db3e391a3518788b1baf361cbd96cfa63a1ec54b1d19c5502f1189722a3bd8fca6cb0144c62346c811457531ec9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
